#if !canImport(ObjectiveC)
import XCTest

extension DicewareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DicewareTests = [
        ("testBitsToWords", testBitsToWords),
        ("testWordlists", testWordlists),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DicewareTests.__allTests__DicewareTests),
    ]
}
#endif
